In [1]:
import poolparty as pp
bg_L = 20
ins_L = 5
with pp.Party() as party:
    bg = pp.from_seqs(['A'*bg_L, 'T'*bg_L]).named('bg').iteration_order(3)
    ins = pp.get_kmers(length=ins_L, mode='hybrid', hybrid_mode_num_states=2).named('insert').iteration_order(1)
    res = pp.replacement_scan(bg_pool=bg, ins_pool=ins, spacer_str='.', mode='hybrid', hybrid_mode_num_states=2, iteration_order=2)
res.print_tree()
pp.generate_seqs(pool=res, num_complete_iterations=1, seed=3)['seq']

pool[5] (pool, n=8)
└── op[4]:join [op=join, mode=fixed, n=1]
    ├── pool[2] (pool, n=4)
    │   └── op[2]:breakpoint_scan [op=breakpoint_scan, mode=hybrid, n=2]
    │       └── bg (pool, n=2)
    │           └── bg.op [op=from_seqs, mode=sequential, n=2]
    ├── insert (pool, n=2)
    │   └── insert.op [op=get_kmers, mode=hybrid, n=2]
    └── pool[4] (pool, n=4)
        └── op[3]:seq_slice [op=seq_slice, mode=fixed, n=1]
            └── pool[3] (pool, n=4)
                └── op[2]:breakpoint_scan [op=breakpoint_scan, mode=hybrid, n=2]
                    └── bg (pool, n=2)
                        └── bg.op [op=from_seqs, mode=sequential, n=2]

0    AAAAAAAAAAAAA.TCGCT.AA
1    TTTTTTTTTTTTT.TCGCT.TT
2    AAAAAAAAA.TCGCT.AAAAAA
3    TTTTTTTTT.TCGCT.TTTTTT
4    AAAAAAAAAAAAA.CGGTG.AA
5    TTTTTTTTTTTTT.CGGTG.TT
6    AAAAAAAAA.CGGTG.AAAAAA
7    TTTTTTTTT.CGGTG.TTTTTT
Name: seq, dtype: object

In [2]:
import statecounter as sc

with sc.Manager() as mgr:
    A = sc.Counter(2).named('A')
    B = sc.Counter(3).named('B')
    C = sc.stack([A,B,A]).named('C')
    D = sc.repeat(A,3).named('D')
    
display(C.get_iteration_df().T)
display(D.get_iteration_df().T)

C     0     1     2     3     4     5     6
A     0     1  None  None  None     0     1
B  None  None     0     1     2  None  None

D  0  1  2  3  4  5
A  0  1  0  1  0  1